careers/careers/urls.py
from django.conf.urls import url

from . import views
from .feeds import LatestPositionsFeed

urlpatterns = [
    url(r'^position/(?P<source>[\w]+)/(?P<job_id>[\w]+)/$', views.PositionDetailView.as_view(),
        name='careers.position'),
    url(r'^$', views.HomeView.as_view(), name='careers.home'),
    url(r'^feed/$', LatestPositionsFeed(), name='careers.feed'),
    url(r'^listings/$', views.PositionListView.as_view(), name='careers.listings'),
    url(r'^internships/$', views.InternshipsView.as_view(), name='careers.internships'),
    url(r'^benefits/$', views.BenefitsView.as_view(), name='careers.benefits'),
]

careers/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.static import serve as servestatic

from .base import views

urlpatterns = [
    url(r'', include('careers.careers.urls')),

    # contribute.json url
    url(r'^(?P<path>contribute\.json)$', servestatic,
        kwargs={'document_root': settings.ROOT}),

    # Generate a robots.txt
    url(r'^robots\.txt$', views.robots, name='robots'),
    url(r'^404\.html$', views.custom_404, name='404'),
]

handler404 = 'careers.base.views.custom_404'

careers/careers/models.py
from datetime import datetime
from itertools import chain

from django.urls import reverse

from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Position(models.Model):
    job_id = models.CharField(max_length=10)
    title = models.CharField(max_length=100)
    department = models.CharField(max_length=100)
    location = models.CharField(max_length=500)
    job_locations = models.CharField(max_length=500, default='')
    is_mofo = models.BooleanField(default=False)
    description = models.TextField()
    apply_url = models.URLField()
    source = models.CharField(max_length=100)
    position_type = models.CharField(max_length=100)
    updated_at = models.DateTimeField(default=datetime.utcnow)

    class Meta:
        ordering = ('department', 'title',)

    def __str__(self):
        return '{}@{}'.format(self.job_id, self.source)

    @property
    def location_list(self):
        return sorted(self.location.split(','))

    def get_absolute_url(self):
        return reverse('careers.position',
                       kwargs={'source': self.source, 'job_id': self.job_id})

    @classmethod
    def position_types(cls):
        return sorted(set(cls.objects.values_list('position_type', flat=True)))

    @classmethod
    def locations(cls):
        return sorted(set(
            location.strip() for location in chain(
                *[locations.split(',') for locations in
                  cls.objects.values_list('location', flat=True)])))

    @classmethod
    def categories(cls):
        return sorted(set(cls.objects.values_list('department', flat=True)))

careers/careers/forms.py
from django import forms

from careers.careers.models import Position


class PositionFilterForm(forms.Form):
    team = forms.ChoiceField(widget=forms.Select(attrs={'autocomplete': 'off'}))
    position_type = forms.ChoiceField(widget=forms.Select(attrs={'autocomplete': 'off'}))
    location = forms.ChoiceField(widget=forms.Select(attrs={'autocomplete': 'off'}))

    def __init__(self, *args, **kwargs):
        super(PositionFilterForm, self).__init__(*args, **kwargs)

        # Populate position type choices dynamically.
        locations = Position.locations()
        if 'All Offices' in locations:
            locations.remove('All Offices')
        if '' in locations:
            locations.remove('')

        self.fields['location'].choices = (
            [('', 'All Locations')] + [(loc, loc) for loc in locations])

        types = Position.position_types()
        if '' in types:
            types.remove('')

        self.fields['position_type'].choices = (
            [('', 'All Positions')] + [(typ, typ) for typ in types])

        categories = Position.categories()
        if '' in categories:
            categories.remove('')

        self.fields['team'].choices = (
            [('', 'All Teams')] + [(kat, kat) for kat in categories])

careers/base/views.py
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render


def robots(request):
    action = 'Allow' if settings.ENGAGE_ROBOTS else 'Disallow'
    return HttpResponse('User-agent: *\n{}: /'.format(action), content_type='text/plain')


def custom_404(request, exception=None):
    status = 404 if exception else 200
    return render(request, '404.jinja', status=status)

careers/careers/views.py
from django.views.generic import DetailView, ListView, TemplateView
from django.shortcuts import get_object_or_404

from careers.careers.forms import PositionFilterForm
from careers.careers.models import Position
from careers.careers.utils import generate_position_meta_description
from careers.careers.wordpress import get_posts


class HomeView(TemplateView):
    template_name = 'careers/home.jinja'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        featured_post, recent_posts = get_posts()

        context['featured_post'] = featured_post
        context['recent_posts'] = recent_posts
        return context


class InternshipsView(TemplateView):
    template_name = 'careers/internships.jinja'


class BenefitsView(TemplateView):
    template_name = 'careers/benefits.jinja'


class PositionListView(ListView):
    model = Position
    template_name = 'careers/listings.jinja'
    context_object_name = 'positions'

    def get_context_data(self, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)
        context['form'] = PositionFilterForm()
        return context


class PositionDetailView(DetailView):
    model = Position
    context_object_name = 'position'
    template_name = 'careers/position.jinja'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, **self.kwargs)

    def get_context_data(self, **kwargs):
        context = super(PositionDetailView, self).get_context_data(**kwargs)
        position = context['position']

        context['meta_description'] = generate_position_meta_description(position)

        related_positions = (
            Position.objects.filter(department=position.department).exclude(id=position.id))
        context['related_positions'] = related_positions

        return context

careers/base/templates/404.jinja
{% set meta_title = "Mozilla Careers &mdash; Page not found" %}
{% set meta_description = meta_title %}
{% extends "base.jinja" %}

{% block site_ie8 %}
  {{ super() }}
  <link href="{{ static('css/careers-ie8.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
<section id="error" class="contain">
    <h1>Page not found!</h1>
    <p>
      Sorry, but we couldn't find the job listing or page you're looking for.
      <a href="{{ url('careers.listings') }}">Check out all the listings</a> for all
      careers at Mozilla.
    </p>
</section>
{% endblock %}

careers/base/templates/500.jinja
{% set meta_title = "Mozilla Careers &mdash; Error" %}
{% set meta_description = meta_title %}
{% extends "base.jinja" %}

{% block site_ie8 %}
  {{ super() }}
  <link href="{{ static('css/careers-ie8.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
<section id="error" class="contain">
    <h1>Sorry, but something went wrong!</h1>

    <p>
      Sorry, but something went wrong on our end and we couldn't process
      your request. You can reload the page to try again, or
      <a href="{{ url('careers.listings') }}">check out all the listings</a> for all
      careers at Mozilla.
    </p>
</section>
{% endblock %}

careers/base/templates/base.jinja
{% set default_slug = "Mozilla Careers &mdash; Feel good about your work again" %}
<!DOCTYPE html>
<html lang="{{ LANG }}" dir="{{ DIR }}" class="no-js"
      data-ga-code="{{ settings.GA_ACCOUNT_CODE }}"
      data-gtm-code="{{ settings.GTM_ACCOUNT_CODE }}">
  <head>
    {# meta #}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{{ meta_title|default(default_slug, true)|safe }}">
    <meta property="og:description" content="{{ meta_description|default(default_slug, true)|safe }}">
    <meta property="og:image" content="https://careers.mozilla.org{{ meta_image|default(static('img/moz-m.png'), true)|safe }}">
    <meta property="og:image:alt" content="{{ meta_title|default(default_slug, true)|safe }}">
    <meta name="twitter:title" content="{{ meta_title|default(default_slug, true)|safe }}">
    <meta name="twitter:description" content="{{ meta_description|default(default_slug, true)|safe }}">
    <meta name="twitter:image" content="https://careers.mozilla.org{{ meta_image|default(static('img/moz-m.png'), true)|safe }}">
    <meta name="twitter:card" content="summary">
    <meta name="description" content="{{ meta_description|default(default_slug, true)|safe }}">
    <title>{{ meta_title|default(default_slug, true)|safe }}</title>

    {# css #}
    {% block site_css %}
      <link href="{{ static('css/protocol/css/protocol.min.css') }}" rel="stylesheet" />
      <link href="{{ static('css/protocol/css/protocol-extra.min.css') }}" rel="stylesheet" />
      <link href="{{ static('css/careers-new.css') }}" rel="stylesheet" />
    {% endblock %}

    {# js #}
    <script src="{{ static('js/dnt-helper.js') }}"></script>
    <script src="{{ static('js/protocol/protocol-base.min.js') }}"></script>
    <script src="{{ static('js/protocol/protocol-utils.min.js') }}"></script>
    <script src="{{ static('js/protocol/protocol-supports.min.js') }}"></script>

    {# icons #}
    <link rel="shortcut icon" type="image/png" href="{{ static('img/favicon.ico') }}"/>

    {# feeds #}
    <link rel="alternate" type="application/rss+xml"
          href="{{ url('careers.feed') }}" title="Current Mozilla job openings" />

    {% block google_analytics %}
      {# Google Analytics #}
      {% if settings.GTM_ACCOUNT_CODE %}
        <script src="{{ static('js/gtm-snippet.js') }}"></script>
      {% elif settings.GA_ACCOUNT_CODE %}
        <script src="{{ static('js/ga.js') }}"></script>
      {% endif %}
    {% endblock %}

  </head>
  <body id="{% block body_id %}{% endblock %}" class="{% block body_class %}{% endblock %}"
    {%- block body_data %}
    {%- endblock %}>
    {%- if settings.GTM_ACCOUNT_CODE %}
      <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id={{ settings. GTM_ACCOUNT_CODE }}"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
      </noscript>
    {%- endif %}

    {% include "base/header.jinja" %}

    <div id="wrapper" class="mzp-l-content mzp-t-mozilla">
      <main role="main">

        {% block content %}{% endblock %}

      </main>
    </div><!-- /#wrapper -->

    {% block site_footer %}
      {% include "base/footer.jinja" %}
    {% endblock %}

    {# js #}
    {% block site_js %}
      {% if settings.GA_ACCOUNT_CODE -%}
        <script src="{{ static('js/ga_event-tracking.js') }}"></script>
      {% endif %}
      <script src="{{ static('js/protocol/protocol-navigation.min.js') }}"></script>
      <script src="{{ static('js/protocol/protocol-menu.min.js') }}"></script>
      <script src="{{ static('js/base.js') }}"></script>
    {% endblock %}

  </body>
</html>

careers/base/templates/base/footer.jinja
<footer class="mzp-c-footer" id="colophon">
  <div class="mzp-l-content">
    <nav class="mzp-c-footer-primary">
      <div class="mzp-c-foot-sections">
        <div class="mzp-c-footer-section mzp-c-footer-primary-logo">
          <a href="https://www.mozilla.org/">Mozilla</a>
        </div>
        <div class="mzp-c-footer-section">
          <a target="_blank" href='https://www.glassdoor.com/Overview/Working-at-Mozilla-EI_IE19129.11,18.htm'>
            <img class="glassdoor-logo" src='/static/img/glassdoor_250x90.png' alt="Glassdoor logo">
          </a>
        </div>
      </div>
      <div class="mzp-c-footer-sections">
        <section class="mzp-c-footer-section">
          <h5 class="mzp-c-footer-heading">
            Company
          </h5>
          <ul class="mzp-c-footer-list">
            <li><a href="https://www.mozilla.org/about/">About</a></li>
            <li><a href="https://blog.mozilla.org/press/">Press Center</a>
          </ul>
        </section>
        <section class="mzp-c-footer-section">
          <h5 class="mzp-c-footer-heading">
            Resources
          </h5>
          <ul class="mzp-c-footer-list">
            <li><a href="https://www.mozilla.org/privacy/">Privacy</a></li>
            <li><a href="https://www.mozilla.org/contact/">Contact</a></li>
          </ul>
        </section>
      </div>
    </nav>
    <nav class="mzp-c-footer-secondary">
      <ul class="mzp-c-footer-links-social">
        <li><a class="twitter" href="https://twitter.com/mozilla">Twitter<span> (@mozilla)</span></a></li>
        <li><a class="instagram" href="https://www.instagram.com/mozilla/">Instagram<span> (@mozilla)</span></a></li>
      </ul>
      <div class="mzp-c-footer-legal">
        <p class="mzp-c-footer-license">
            Visit Mozilla Corporation’s not-for-profit parent, the <a href="https://foundation.mozilla.org">Mozilla Foundation</a>.
            Portions of this content are ©1998–{{ thisyear() }} by individual mozilla.org
            contributors. Content available under a <a rel="license" href="https://www.mozilla.org/foundation/licensing/website-content/">Creative Commons license</a>.
        </p>
      </div>
    </nav>
  </div>
</footer>

careers/base/templates/base/header.jinja
<div class="mzp-c-navigation">
  <div class="mzp-c-navigation-l-content">
    <div class="mzp-c-navigation-container">
      <button class="mzp-c-navigation-menu-button" type="button" aria-controls="patterns.organisms.navigation.navigation">Menu</button>

      <div class="mzp-c-navigation-logo">
        <a href="{{ url('careers.home') }}" id="ga-nav-home-logo"></a>
      </div>

      <div class="mzp-c-navigation-items" id="patterns.organisms.navigation.navigation">
        <div class="mzp-c-navigation-menu">

          <nav class="mzp-c-menu mzp-is-basic">
            <ul class="mzp-c-menu-category-list">
              <li class="mzp-c-menu-category">
                <a href="{{ url('careers.listings') }}" class="mzp-c-menu-title" id="ga-nav-listing">Jobs</a>
              </li>
              <li class="mzp-c-menu-category">
                <a href="https://blog.mozilla.org/careers/" class="mzp-c-menu-title" id="ga-nav-life" target="_blank">Life at Mozilla</a>
              </li>
              <li class="mzp-c-menu-category">
                <a href="{{ url('careers.home')|urlparams(hash='locations') }}" class="mzp-c-menu-title" id="ga-nav-locations">Locations</a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

careers/careers/templates/careers/benefits.jinja
{% extends "base.jinja" %}

{% set meta_title = "Mozilla Careers &mdash; Feel good about your work again." %}
{% set meta_description = "Mozilla Careers &mdash; Feel good about your work again. At Mozilla, you can pursue your future while working to protect the future of the internet for everyone, everywhere." %}

{% block body_class %}benefits-page{% endblock %}

{% block content %}

<section class="mzp-c-hero mzp-t-dark page-hero"></section>

<section class="mzp-l-content">
    <h2>Benefits</h2>
    <p>
        To ensure our employees and their families feel safe, cared for, and supported, we offer world-class benefits, including: 
    </p>
    <ul class="mzp-u-list-styled">
        <li>Flexible work environment (nearly half of Mozillians work remotely)</li>
        <li>Industry-leading paid parental leave (up to 26 weeks of fully paid leave for childbearing parents and up to 12 weeks for non-childbearing parents)</li>
        <li>Generous medical, dental and vision coverage for you and your family (including no payroll deductions in most countries)</li>
        <li>Reimbursement for professional development (up to $3,000 USD/year)</li>
        <li>A work setup including the latest hardware and software of your choice</li>
        <li>Wellness programs—we reimburse up to $1700 USD/year for a variety of expenses like child and elder care, mental wellness, and personal enrichment</li> 
    </ul>
</section>

<div class="mzp-l-content">
  <div class="centered">
    <a class="mzp-c-button" href="{{ url('careers.listings') }}">Apply Now</a>
  </div>
</div>

{% endblock %}

careers/careers/templates/careers/listings.jinja
{% extends "base.jinja" %}

{% set meta_title = "Mozilla Careers &mdash; All open positions at Mozilla" %}
{% set meta_description = "Mozilla Careers &mdash; We have a mighty mandate, serving hundreds of millions of people. Add a culture of exploration, and there is always a new way to learn and grow here." %}

{% block body_class %}listings-page{% endblock %}

{% block content %}

<section class="mzp-c-hero mzp-t-dark page-hero">
  <div class="mzp-l-content">
    <div class="mzp-c-hero-body">
      <h1 class="mzp-c-hero-title">Feel good about your work again</h1>

      <div class="mzp-c-hero-desc">
        <p>
          Join us.
        </p>
      </div>
    </div>
  </div>
</section>

<section class="mzp-l-content">
  <h2>Listings</h2>

  <form id="listings-filters">
    <div class="listings-filter listings-filter-location">
      {{ form.location }}
      <label for="id_location" class="visually-hidden">Location</label>
    </div>

    {# hidden input keeps JS/python working, but removes the old form field #}
    <input type="hidden" id="id_position_type" name="position_type" value=""/>

    <div class="listings-filter listings-filter-name">
      {{ form.team }}
      <label for="id_team" class="visually-hidden">Team</label>
    </div>
  </form>
</section>

<section class="mzp-l-content">
  <table class="listings-positions" id="listings-positions">
    <thead>
      <tr>
        <th class="title" scope="col"><h4>Job Title</h4></th>
        <th class="location" scope="col"><h4>Location</h4></th>
        <th class="name" scope="col"><h4>Team</h4></th>
      </tr>
    </thead>
    <tbody>
    {% for position in positions %}
      <tr class="position"
          data-team="{{ position.department }},"
          data-type="{{ position.position_type }},"
          data-location="{{ position.location }},">
        <td class="title"><a href="{{ position.get_absolute_url() }}">{{ position.title }}</a></td>
        <td class="location">{{ position.job_locations }}</td>
        <td class="name">{{ position.department }}</td>
      </tr>
    {% endfor %}
      <tr class="empty-filter-message hidden" id="empty-filter-message">
        <td colspan="4">
          <p>No jobs found that match the selected filters.</p>
        </td>
      </tr>
    </tbody>
  </table>
</section>
{% endblock %}


{% block site_js %}
  {{ super() }}
  <script src="{{ static('js/listings.js') }}"></script>
  <script src="{{ static('js/filters.js') }}"></script>
{% endblock %}

careers/careers/templates/careers/macros.jinja
{% macro breadcrumbs() -%}
  <header id="jobs-header">
    <p id="breadcrumbs">
      <a href="http://www.mozilla.org/{{ LANG }}" class="home">Home</a>
      <strong>»</strong>
      <a href="http://www.mozilla.org/{{ LANG }}/about">About</a>
      <strong>»</strong>
      {% for crumb in varargs -%}
        <a href="{{ crumb[0] }}">{{ crumb[1] }}</a>
        <strong>»</strong>
      {% endfor -%}
      <span>{{ kwargs.last }}</span>
    </p>
  </header>
{% endmacro -%}

{% macro position_listing(category) -%}
  <li>
    <h2>{{ category.name }}</h2>
    <ul>
      {% for position in category.position_set.order_by('title') %}
        <li>
          <a href="{{ url('careers.position', job_id=position.job_id) }}"
             data-jobtype="{{ position.job_type.lower() }}"
             alt="{{ position.title }}"
             title="{{ position.title }}">{{ position.title }}</a>
        </li>
      {% endfor %}
    </ul>
  </li>
{% endmacro -%}

careers/careers/templates/careers/position.jinja
{% extends "base.jinja" %}

{% set meta_title = "Mozilla Careers &mdash; " + position.title + " &mdash; Open Positions" %}
{% set meta_description = "Mozilla Careers &mdash; " + meta_description|truncate(175, end='…') %}

{% block body_class %}position-page{% endblock %}

{% block content %}
<section class="job-post" id="job-post">
  <div class="job-row">
    <div>
      <div class="job-title">
        <strong>{{ position.title }}</strong>
      </div>
      <div class="title-location">
        at
        {% if position.is_mofo %}
          Mozilla Foundation
        {% else %}
          Mozilla Corporation
        {% endif %}
      </div>
      <dl class="mzp-u-list-styled">
        {% if not position.is_mofo %}
          <dt class="job-post-team-head">Team:</dt>
          <dd class="job-post-team">{{ position.department }}</dd>
        {% endif %}
        <dt class="job-post-location-head">Locations:</dt>
        <dd class="job-post-location">{{ position.job_locations }}</dd>
      </dl>
    </div>
    <div class="appy-btn">
      <a href="{{ position.apply_url }}" class="mzp-c-button">Apply Now</a>
    </div>
  </div>
  <div class="appy-btn-sm apply-sm">
    <a href="{{ position.apply_url }}" class="mzp-c-button">Apply Now</a>
  </div>
  <div>
    {{ position.description|safe }}
  </div>
  <div class="c-apply-button-container">
    <a href="{{ position.apply_url }}" class="mzp-c-button">Apply for this job</a>
    <small>
      <a rel="external" href="https://docs.google.com/document/d/e/2PACX-1vTEeCImDA-kqr0wm3JwfOv_2MS5FZ8oyL2pEWfVsZbeO87E41r2wePoOhppQ4qX6w/pub">Applicant Privacy Notice</a>
    </small>
  </div>
</section>

<section id="why" class="mzp-c-call-out">
  <div class="mzp-l-content">
    <h2 class="mzp-c-call-out-title">Why Mozilla?</h2>
    <p class="mzp-c-call-out-desc">
      At Mozilla, we’re serving humanity—by maintaining a safe, open internet—while also
      helping the individual humans employed here to reach their personal and
      professional goals. With a relatively small team serving hundreds of millions of
      people, a culture of exploration, and a commitment to mentorship, opportunities
      abound to learn and grow at Mozilla.
    </p>
  </div>
</section>

<br />

<section class="mzp-l-card-third">
  <div class="mzp-c-card">
    <div class="mzp-c-card-content">
      <h3 class="mzp-c-card-title">Our values drive our actions</h3>
      <div class="mzp-c-card-desc">
        <ul class="mzp-u-list-styled">
          <li>
            Purpose is built into our work, with our mission driving every decision
          </li>
          <li>We challenge assumptions, the status quo, ourselves, and each other</li>
          <li>
            We are transparent: in our code, our business partnerships, and our everyday
            interactions
          </li>
          <li>
            We seek out people from diverse backgrounds and with perspectives different
            from our own
          </li>
          <li>We pair purpose with performance and put people ahead of profit</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="mzp-c-card">
    <div class="mzp-c-card-content">
      <h3 class="mzp-c-card-title">Our impact is global</h3>
      <div class="mzp-c-card-desc">
        <ul class="mzp-u-list-styled">
          <li>700+ paid staff from over 30 countries</li>
          <li>Thousands of volunteer contributors across six continents</li>
          <li>
            9 global offices: Mountain View, San Francisco, Portland, Vancouver,
            Toronto, Paris, London, Berlin, and Beijing
          </li>
          <li>Hundreds of home offices globally</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="mzp-c-card">
    <div class="mzp-c-card-content">
      <h3 class="mzp-c-card-title">Our benefits are world-class</h3>
      <div class="mzp-c-card-desc">
        <ul class="mzp-u-list-styled">
          <li>Flexible work environment (nearly half of Mozillians work remotely)</li>
          <li>
            Industry-leading paid parental leave (up to 26 weeks of fully paid leave for
            childbearing parents and up to 12 weeks for non-childbearing parents)
          </li>
          <li>Reimbursement for professional development (up to $3,000/year)</li>
          <li>A work setup including the latest hardware and software of your choice</li>
        </ul>
      </div>
    </div>
  </div>
</section>

{% endblock %}